import product1 from "../images/product/tp-1.jpg";
import product2 from "../images/product/tp-2.jpg";
import product3 from "../images/product/tp-3.jpg";
import product4 from "../images/product/tp-4.jpg";
import product5 from "../images/product/tp-5.jpg";
import product6 from "../images/product/tp-7.jpg";
import product7 from "../images/product/tp-9.jpg";
import product8 from "../images/product/tp-10.jpg";

import productnav1 from "../images/product/nav/product-nav-1.jpg";
import productnav2 from "../images/product/nav/product-nav-2.jpg";
import productnav3 from "../images/product/nav/product-nav-3.jpg";

import productnavbg1 from "../images/product/nav/product-nav-big-1.jpg";
import productnavbg2 from "../images/product/nav/product-nav-big-2.jpg";
import productnavbg3 from "../images/product/nav/product-nav-big-3.jpg";

export const dbApp = {
  categories: [
    {
      id: 1,
      name: "Điện thoại",
      img: "",
    },
    {
      id: 2,
      name: "Máy tính bảng",
      img: "",
    },
    {
      id: 3,
      name: "Âm thanh",
      img: "",
    },
  ],
  products: [
    {
      id: 1,
      name: "iPhone 13",
      image: product1,
      images: [
        {
          imagesm: productnav1,
          imagebg: productnavbg1,
        },
        {
          imagesm: productnav2,
          imagebg: productnavbg2,
        },
        {
          imagesm: productnav3,
          imagebg: productnavbg3,
        },
      ],
      price: "25.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 1,
      describe:
        "Tương tự năm ngoái, Apple cũng sẽ cho ra mắt 4 phiên bản là iPhone 13, 13 mini, 13 Pro và 13 Pro Max.",
    },
    {
      id: 2,
      name: "iPhone 12",
      image: product1,
      price: "20.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 1,
    },
    {
      id: 3,
      name: "iPhone 11",
      image: product1,
      price: "15.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 1,
    },
    {
      id: 4,
      name: "iPhone 11 Pro Max",
      image: product1,
      price: "15.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 1,
    },
    {
      id: 5,
      name: "iPhone 11 Pro",
      image: product1,
      price: "15.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 1,
    },
    {
      id: 6,
      name: "iPhone XS Max",
      image: product2,
      price: "15.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 2,
    },
    {
      id: 7,
      name: "iPhone XS",
      image: product2,
      price: "15.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 2,
    },
    {
      id: 8,
      name: "iPhone X",
      image: product2,
      price: "15.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 2,
    },
    {
      id: 9,
      name: "iPhone SE 2022",
      image: product2,
      price: "15.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 2,
    },
    {
      id: 10,
      name: "iPhone SE 2020",
      image: product2,
      price: "15.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 2,
    },
    {
      id: 11,
      name: "iPhone 8 Plus",
      image: product3,
      price: "15.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 3,
    },
    {
      id: 12,
      name: "iPhone 8",
      image: product3,
      price: "15.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 3,
    },
    {
      id: 13,
      name: "iPhone 7 Plus",
      image: product3,
      price: "15.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 3,
    },
    {
      id: 14,
      name: "Samsung Galaxy S22",
      image: product3,
      price: "25.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Samsung",
      categoryId: 3,
    },
    {
      id: 15,
      name: "Samsung Galaxy A32",
      image: product3,
      price: "20.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Samsung",
      categoryId: 3,
    },
    {
      id: 16,
      name: "Samsung Galaxy Note 20",
      image: product4,
      price: "15.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Samsung",
      categoryId: 4,
    },
    {
      id: 17,
      name: "Apple iPad Pro 11",
      image: product4,
      price: "25.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "iPadPro",
      categoryId: 4,
    },
    {
      id: 18,
      name: "Apple iPad Pro 12.9",
      image: product4,
      price: "20.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "iPadPro",
      categoryId: 4,
    },
    {
      id: 19,
      name: "Tai nghe Bluetooth Apple AirPods 2",
      image: product4,
      price: "5.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      describe: "",
      categoryId: 4,
    },
    {
      id: 20,
      name: "Tai nghe chụp tai Sony WH-1000XM4",
      image: product4,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 4,
    },
    {
      id: 21,
      name: "PhuKien",
      image: product5,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 5,
    },
    {
      id: 22,
      name: "PhuKien",
      image: product5,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 5,
    },
    {
      id: 23,
      name: "PhuKien",
      image: product5,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 5,
    },
    {
      id: 24,
      name: "PhuKien",
      image: product5,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 5,
    },
    {
      id: 25,
      name: "PhuKien",
      image: product5,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 5,
    },
    {
      id: 26,
      name: "Xbox",
      image: product6,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 6,
    },
    {
      id: 27,
      name: "Xbox",
      image: product6,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 6,
    },
    {
      id: 28,
      name: "Xbox",
      image: product6,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 6,
    },
    {
      id: 29,
      name: "Xbox",
      image: product6,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 6,
    },
    {
      id: 30,
      name: "Xbox",
      image: product6,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 6,
    },
    {
      id: 31,
      name: "Tai Nghe",
      image: product7,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 7,
    },
    {
      id: 32,
      name: "Tai Nghe",
      image: product7,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 7,
    },
    {
      id: 33,
      name: "Tai Nghe",
      image: product7,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 7,
    },
    {
      id: 34,
      name: "Tai Nghe",
      image: product7,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 7,
    },
    {
      id: 35,
      name: "Tai Nghe",
      image: product7,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 7,
    },
    {
      id: 36,
      name: "Camera",
      image: product8,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 8,
    },
    {
      id: 37,
      name: "Camera",
      image: product8,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 8,
    },
    {
      id: 38,
      name: "Camera",
      image: product8,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 8,
    },
    {
      id: 39,
      name: "Camera",
      image: product8,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 8,
    },
    {
      id: 40,
      name: "Camera",
      image: product8,
      price: "2.000.000 đ",
      offer: "15%",
      rate: "4.9",
      review: 10 + " đánh giá",
      company: "Apple",
      categoryId: 8,
    },
  ],
};
